service: offer-service

frameworkVersion: '2'

provider:
  name: aws
  apiGateway:
    apiKeys:
      - name: fideltest-key
        value: v3IPj3dPvT62rJYm3Ho7d2owPMxyYQ7x5kJNWcsH
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment:
    DEFAULT_UUID: "3693ac7e-3e2b-432c-8c60-2b786453ca9b"
    OFFER_TABLE: "offer-dev"
    LOCATION_TABLE: "location-dev"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

functions:
  hello:
    handler: api/handler.hello
    memorySize: 128
    description: Hello world
    events:
      - http: 
          path: offer
          method: get
  createOffers:
    handler: api/offer.create
    memorySize: 128
    description: Create offers for Brands
    events:
      - http: 
          path: offer
          method: post
          private: true

resources:
  Resources:
    OffersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.OFFER_TABLE}
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S" 
          -
            AttributeName: "brandId"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
        GlobalSecondaryIndexes:
          -
            IndexName: "brandIdIndex"
            KeySchema:
              -
                AttributeName: "brandId"
                KeyType: "HASH"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    LocationsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.LOCATION_TABLE}
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S" 
          -
            AttributeName: "brandId"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
        GlobalSecondaryIndexes:
          -
            IndexName: "brandIdIndex"
            KeySchema:
              -
                AttributeName: "brandId"
                KeyType: "HASH"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
